# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    info:
      title: Product API
      description: Документация по API для управления продуктами.
      version: 1.0.0

  areas:
    default:
      path_patterns:
        - ^/api/
      documentation:
        components:
          securitySchemes:
            Bearer:
              type: http
              scheme: bearer
              bearerFormat: JWT
        security:
          - Bearer: []
