nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://online-proposal.local:3000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
        expose_headers: ['Authorization']
        max_age: 99999999
    paths:
        '^/': ~